# Generated by Django 5.2 on 2025-04-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autogen_mailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='user',
        ),
    ]
