# Generated by Django 5.2 on 2025-04-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autogen_mailer', '0003_alter_recipient_options_emailcampaign_scheduled_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedemail',
            name='account',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='account',
        ),
        migrations.RemoveField(
            model_name='emailattachment',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='receivedattachment',
            name='email',
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={},
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='error',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='message_id',
        ),
        migrations.DeleteModel(
            name='EmailAccount',
        ),
        migrations.DeleteModel(
            name='EmailAttachment',
        ),
        migrations.DeleteModel(
            name='ReceivedAttachment',
        ),
        migrations.DeleteModel(
            name='ReceivedEmail',
        ),
    ]
