# Generated by Django 5.2 on 2025-04-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogen_mailer', '0004_remove_receivedemail_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_message_id', models.CharField(max_length=255)),
                ('reply_message_id', models.CharField(max_length=255)),
                ('reply_content', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('reply_sent', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='autogen_mailer.emailcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='autogen_mailer.recipient')),
            ],
            options={
                'unique_together': {('reply_message_id', 'recipient')},
            },
        ),
    ]
